name: Sync from Account A
on:
  schedule:
    - cron: '0 * * * *'  # Hourly sync
  workflow_dispatch:     # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git remote add source https://github.com/BawadharaniSree/MedNext2025.git
          git fetch source
          git merge source/main --allow-unrelated-histories
          git push origin main
